# Generated by Django 3.1.7 on 2021-06-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pot_id', models.IntegerField(default=0)),
                ('humidity', models.FloatField(default=0)),
                ('temperature', models.FloatField(default=0)),
                ('light', models.FloatField(default=0)),
                ('water_flow', models.FloatField(default=0)),
                ('fertilizer_flow', models.FloatField(default=0)),
                ('water_level', models.FloatField(default=0)),
                ('fertilizer_level', models.FloatField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
