# Generated by Django 3.1.7 on 2021-03-30 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_service', '0002_auto_20210330_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='date',
            field=models.TimeField(default=datetime.time(15, 27, 30, 301695)),
        ),
    ]
