# Generated by Django 3.1.7 on 2021-05-01 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_service', '0004_auto_20210401_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='date',
            field=models.TimeField(default=datetime.time(0, 33, 5, 520938)),
        ),
    ]
