# Generated by Django 3.1.7 on 2021-05-14 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_service', '0005_auto_20210502_0033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='illumination',
            new_name='light',
        ),
        migrations.AlterField(
            model_name='state',
            name='date',
            field=models.TimeField(default=datetime.time(19, 45, 24, 378922)),
        ),
    ]
